# Generated by Django 3.2.13 on 2022-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220614_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='num',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
