# Generated by Django 3.2.13 on 2022-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productimage_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='num',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_represent',
            field=models.BooleanField(default=False),
        ),
    ]
