# Generated by Django 3.2.13 on 2022-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20220617_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.FloatField(default=0),
        ),
    ]
