# Generated by Django 3.2.13 on 2022-06-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
    ]
