# Generated by Django 3.2.13 on 2022-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='이메일')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='비밀번호')),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
