# Generated by Django 3.2.13 on 2022-07-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220628_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=255, verbose_name='핸드폰')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('card_number', models.CharField(max_length=255, verbose_name='결제카드번호')),
            ],
        ),
    ]
